//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGOTouch.ServiceTicketPesada {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComprobanteCliente", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class ComprobanteCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdTipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ImporteSubtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ImporteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArhivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAZONSOCIAL_PRODELSURField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUC_PRODELSURField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoMonedaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correlativo {
            get {
                return this.CorrelativoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelativoField, value) != true)) {
                    this.CorrelativoField = value;
                    this.RaisePropertyChanged("Correlativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaOperacion {
            get {
                return this.FechaOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaOperacionField, value) != true)) {
                    this.FechaOperacionField = value;
                    this.RaisePropertyChanged("FechaOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComprobante {
            get {
                return this.IdComprobanteField;
            }
            set {
                if ((this.IdComprobanteField.Equals(value) != true)) {
                    this.IdComprobanteField = value;
                    this.RaisePropertyChanged("IdComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTipoComprobante {
            get {
                return this.IdTipoComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTipoComprobanteField, value) != true)) {
                    this.IdTipoComprobanteField = value;
                    this.RaisePropertyChanged("IdTipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImporteSubtotal {
            get {
                return this.ImporteSubtotalField;
            }
            set {
                if ((this.ImporteSubtotalField.Equals(value) != true)) {
                    this.ImporteSubtotalField = value;
                    this.RaisePropertyChanged("ImporteSubtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ImporteTotal {
            get {
                return this.ImporteTotalField;
            }
            set {
                if ((this.ImporteTotalField.Equals(value) != true)) {
                    this.ImporteTotalField = value;
                    this.RaisePropertyChanged("ImporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Impuesto {
            get {
                return this.ImpuestoField;
            }
            set {
                if ((this.ImpuestoField.Equals(value) != true)) {
                    this.ImpuestoField = value;
                    this.RaisePropertyChanged("Impuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceState {
            get {
                return this.InvoiceStateField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceStateField, value) != true)) {
                    this.InvoiceStateField = value;
                    this.RaisePropertyChanged("InvoiceState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArhivo {
            get {
                return this.NombreArhivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArhivoField, value) != true)) {
                    this.NombreArhivoField = value;
                    this.RaisePropertyChanged("NombreArhivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAZONSOCIAL_PRODELSUR {
            get {
                return this.RAZONSOCIAL_PRODELSURField;
            }
            set {
                if ((object.ReferenceEquals(this.RAZONSOCIAL_PRODELSURField, value) != true)) {
                    this.RAZONSOCIAL_PRODELSURField = value;
                    this.RaisePropertyChanged("RAZONSOCIAL_PRODELSUR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC_PRODELSUR {
            get {
                return this.RUC_PRODELSURField;
            }
            set {
                if ((object.ReferenceEquals(this.RUC_PRODELSURField, value) != true)) {
                    this.RUC_PRODELSURField = value;
                    this.RaisePropertyChanged("RUC_PRODELSUR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMoneda {
            get {
                return this.TipoMonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoMonedaField, value) != true)) {
                    this.TipoMonedaField = value;
                    this.RaisePropertyChanged("TipoMoneda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TICKET_PESADA", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class TICKET_PESADA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DsctoAguaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GiExcelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuiaRemisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdContactoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdExcelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdGuiaIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdGuiaRemisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdLaboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProcesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSacoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTicketPesadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTicketPesadaZonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoCafeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KgBrutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KgNetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KgSecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NroSacoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PesoSacoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cosecha {
            get {
                return this.CosechaField;
            }
            set {
                if ((this.CosechaField.Equals(value) != true)) {
                    this.CosechaField = value;
                    this.RaisePropertyChanged("Cosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DsctoAgua {
            get {
                return this.DsctoAguaField;
            }
            set {
                if ((this.DsctoAguaField.Equals(value) != true)) {
                    this.DsctoAguaField = value;
                    this.RaisePropertyChanged("DsctoAgua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModifica {
            get {
                return this.FechaModificaField;
            }
            set {
                if ((this.FechaModificaField.Equals(value) != true)) {
                    this.FechaModificaField = value;
                    this.RaisePropertyChanged("FechaModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaTicket {
            get {
                return this.FechaTicketField;
            }
            set {
                if ((this.FechaTicketField.Equals(value) != true)) {
                    this.FechaTicketField = value;
                    this.RaisePropertyChanged("FechaTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GiExcel {
            get {
                return this.GiExcelField;
            }
            set {
                if ((object.ReferenceEquals(this.GiExcelField, value) != true)) {
                    this.GiExcelField = value;
                    this.RaisePropertyChanged("GiExcel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuiaRemision {
            get {
                return this.GuiaRemisionField;
            }
            set {
                if ((object.ReferenceEquals(this.GuiaRemisionField, value) != true)) {
                    this.GuiaRemisionField = value;
                    this.RaisePropertyChanged("GuiaRemision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdContactoCliente {
            get {
                return this.IdContactoClienteField;
            }
            set {
                if ((this.IdContactoClienteField.Equals(value) != true)) {
                    this.IdContactoClienteField = value;
                    this.RaisePropertyChanged("IdContactoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdExcel {
            get {
                return this.IdExcelField;
            }
            set {
                if ((object.ReferenceEquals(this.IdExcelField, value) != true)) {
                    this.IdExcelField = value;
                    this.RaisePropertyChanged("IdExcel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdGuiaIngreso {
            get {
                return this.IdGuiaIngresoField;
            }
            set {
                if ((this.IdGuiaIngresoField.Equals(value) != true)) {
                    this.IdGuiaIngresoField = value;
                    this.RaisePropertyChanged("IdGuiaIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdGuiaRemision {
            get {
                return this.IdGuiaRemisionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGuiaRemisionField, value) != true)) {
                    this.IdGuiaRemisionField = value;
                    this.RaisePropertyChanged("IdGuiaRemision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdLaboratorio {
            get {
                return this.IdLaboratorioField;
            }
            set {
                if ((this.IdLaboratorioField.Equals(value) != true)) {
                    this.IdLaboratorioField = value;
                    this.RaisePropertyChanged("IdLaboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLocal {
            get {
                return this.IdLocalField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLocalField, value) != true)) {
                    this.IdLocalField = value;
                    this.RaisePropertyChanged("IdLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProceso {
            get {
                return this.IdProcesoField;
            }
            set {
                if ((this.IdProcesoField.Equals(value) != true)) {
                    this.IdProcesoField = value;
                    this.RaisePropertyChanged("IdProceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSaco {
            get {
                return this.IdSacoField;
            }
            set {
                if ((this.IdSacoField.Equals(value) != true)) {
                    this.IdSacoField = value;
                    this.RaisePropertyChanged("IdSaco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTicketPesada {
            get {
                return this.IdTicketPesadaField;
            }
            set {
                if ((this.IdTicketPesadaField.Equals(value) != true)) {
                    this.IdTicketPesadaField = value;
                    this.RaisePropertyChanged("IdTicketPesada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTicketPesadaZona {
            get {
                return this.IdTicketPesadaZonaField;
            }
            set {
                if ((this.IdTicketPesadaZonaField.Equals(value) != true)) {
                    this.IdTicketPesadaZonaField = value;
                    this.RaisePropertyChanged("IdTicketPesadaZona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoCafe {
            get {
                return this.IdTipoCafeField;
            }
            set {
                if ((this.IdTipoCafeField.Equals(value) != true)) {
                    this.IdTipoCafeField = value;
                    this.RaisePropertyChanged("IdTipoCafe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KgBruto {
            get {
                return this.KgBrutoField;
            }
            set {
                if ((this.KgBrutoField.Equals(value) != true)) {
                    this.KgBrutoField = value;
                    this.RaisePropertyChanged("KgBruto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KgNeto {
            get {
                return this.KgNetoField;
            }
            set {
                if ((this.KgNetoField.Equals(value) != true)) {
                    this.KgNetoField = value;
                    this.RaisePropertyChanged("KgNeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KgSeco {
            get {
                return this.KgSecoField;
            }
            set {
                if ((this.KgSecoField.Equals(value) != true)) {
                    this.KgSecoField = value;
                    this.RaisePropertyChanged("KgSeco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NroSaco {
            get {
                return this.NroSacoField;
            }
            set {
                if ((this.NroSacoField.Equals(value) != true)) {
                    this.NroSacoField = value;
                    this.RaisePropertyChanged("NroSaco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PesoSaco {
            get {
                return this.PesoSacoField;
            }
            set {
                if ((this.PesoSacoField.Equals(value) != true)) {
                    this.PesoSacoField = value;
                    this.RaisePropertyChanged("PesoSaco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tara {
            get {
                return this.TaraField;
            }
            set {
                if ((this.TaraField.Equals(value) != true)) {
                    this.TaraField = value;
                    this.RaisePropertyChanged("Tara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioModifica {
            get {
                return this.UsuarioModificaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioModificaField, value) != true)) {
                    this.UsuarioModificaField = value;
                    this.RaisePropertyChanged("UsuarioModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRegistroField, value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisTicketPesada_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisTicketPesada_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOLABORATORIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOTICKETPESADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COSECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCLABORATORIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCUSUARIOMODIFICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCUSUARIOREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOCIDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DSCTOAGUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAMODIFICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHATICKETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIAREMISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HUMEDADZONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDCONTACTOCLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDGUIAREMISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDLABORATORIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDLOCALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDPROCESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDSACOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTICKETPESADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTIPOCAFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGBRUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGNETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGSECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NROSACOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PESOSACOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PORCRENDIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TARAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOCAFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOMODIFICAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOREGISTROField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOLABORATORIO {
            get {
                return this.CODIGOLABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOLABORATORIOField, value) != true)) {
                    this.CODIGOLABORATORIOField = value;
                    this.RaisePropertyChanged("CODIGOLABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOTICKETPESADA {
            get {
                return this.CODIGOTICKETPESADAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOTICKETPESADAField, value) != true)) {
                    this.CODIGOTICKETPESADAField = value;
                    this.RaisePropertyChanged("CODIGOTICKETPESADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COSECHA {
            get {
                return this.COSECHAField;
            }
            set {
                if ((this.COSECHAField.Equals(value) != true)) {
                    this.COSECHAField = value;
                    this.RaisePropertyChanged("COSECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCLABORATORIO {
            get {
                return this.DESCLABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCLABORATORIOField, value) != true)) {
                    this.DESCLABORATORIOField = value;
                    this.RaisePropertyChanged("DESCLABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCUSUARIOMODIFICA {
            get {
                return this.DESCUSUARIOMODIFICAField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCUSUARIOMODIFICAField, value) != true)) {
                    this.DESCUSUARIOMODIFICAField = value;
                    this.RaisePropertyChanged("DESCUSUARIOMODIFICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCUSUARIOREGISTRO {
            get {
                return this.DESCUSUARIOREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCUSUARIOREGISTROField, value) != true)) {
                    this.DESCUSUARIOREGISTROField = value;
                    this.RaisePropertyChanged("DESCUSUARIOREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOCIDENTIDAD {
            get {
                return this.DOCIDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.DOCIDENTIDADField, value) != true)) {
                    this.DOCIDENTIDADField = value;
                    this.RaisePropertyChanged("DOCIDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DSCTOAGUA {
            get {
                return this.DSCTOAGUAField;
            }
            set {
                if ((this.DSCTOAGUAField.Equals(value) != true)) {
                    this.DSCTOAGUAField = value;
                    this.RaisePropertyChanged("DSCTOAGUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAMODIFICA {
            get {
                return this.FECHAMODIFICAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAMODIFICAField, value) != true)) {
                    this.FECHAMODIFICAField = value;
                    this.RaisePropertyChanged("FECHAMODIFICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAREGISTRO {
            get {
                return this.FECHAREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAREGISTROField, value) != true)) {
                    this.FECHAREGISTROField = value;
                    this.RaisePropertyChanged("FECHAREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHATICKET {
            get {
                return this.FECHATICKETField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHATICKETField, value) != true)) {
                    this.FECHATICKETField = value;
                    this.RaisePropertyChanged("FECHATICKET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUIAREMISION {
            get {
                return this.GUIAREMISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIAREMISIONField, value) != true)) {
                    this.GUIAREMISIONField = value;
                    this.RaisePropertyChanged("GUIAREMISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> HUMEDADZONA {
            get {
                return this.HUMEDADZONAField;
            }
            set {
                if ((this.HUMEDADZONAField.Equals(value) != true)) {
                    this.HUMEDADZONAField = value;
                    this.RaisePropertyChanged("HUMEDADZONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLIENTE {
            get {
                return this.IDCLIENTEField;
            }
            set {
                if ((this.IDCLIENTEField.Equals(value) != true)) {
                    this.IDCLIENTEField = value;
                    this.RaisePropertyChanged("IDCLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDCONTACTOCLIENTE {
            get {
                return this.IDCONTACTOCLIENTEField;
            }
            set {
                if ((this.IDCONTACTOCLIENTEField.Equals(value) != true)) {
                    this.IDCONTACTOCLIENTEField = value;
                    this.RaisePropertyChanged("IDCONTACTOCLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((this.IDESTADOField.Equals(value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDGUIAREMISION {
            get {
                return this.IDGUIAREMISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.IDGUIAREMISIONField, value) != true)) {
                    this.IDGUIAREMISIONField = value;
                    this.RaisePropertyChanged("IDGUIAREMISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDLABORATORIO {
            get {
                return this.IDLABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDLABORATORIOField, value) != true)) {
                    this.IDLABORATORIOField = value;
                    this.RaisePropertyChanged("IDLABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDLOCAL {
            get {
                return this.IDLOCALField;
            }
            set {
                if ((object.ReferenceEquals(this.IDLOCALField, value) != true)) {
                    this.IDLOCALField = value;
                    this.RaisePropertyChanged("IDLOCAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPROCESO {
            get {
                return this.IDPROCESOField;
            }
            set {
                if ((this.IDPROCESOField.Equals(value) != true)) {
                    this.IDPROCESOField = value;
                    this.RaisePropertyChanged("IDPROCESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDSACO {
            get {
                return this.IDSACOField;
            }
            set {
                if ((this.IDSACOField.Equals(value) != true)) {
                    this.IDSACOField = value;
                    this.RaisePropertyChanged("IDSACO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTICKETPESADA {
            get {
                return this.IDTICKETPESADAField;
            }
            set {
                if ((this.IDTICKETPESADAField.Equals(value) != true)) {
                    this.IDTICKETPESADAField = value;
                    this.RaisePropertyChanged("IDTICKETPESADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTIPOCAFE {
            get {
                return this.IDTIPOCAFEField;
            }
            set {
                if ((this.IDTIPOCAFEField.Equals(value) != true)) {
                    this.IDTIPOCAFEField = value;
                    this.RaisePropertyChanged("IDTIPOCAFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGBRUTO {
            get {
                return this.KGBRUTOField;
            }
            set {
                if ((this.KGBRUTOField.Equals(value) != true)) {
                    this.KGBRUTOField = value;
                    this.RaisePropertyChanged("KGBRUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGNETO {
            get {
                return this.KGNETOField;
            }
            set {
                if ((this.KGNETOField.Equals(value) != true)) {
                    this.KGNETOField = value;
                    this.RaisePropertyChanged("KGNETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGSECO {
            get {
                return this.KGSECOField;
            }
            set {
                if ((this.KGSECOField.Equals(value) != true)) {
                    this.KGSECOField = value;
                    this.RaisePropertyChanged("KGSECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NROSACO {
            get {
                return this.NROSACOField;
            }
            set {
                if ((this.NROSACOField.Equals(value) != true)) {
                    this.NROSACOField = value;
                    this.RaisePropertyChanged("NROSACO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PESOSACO {
            get {
                return this.PESOSACOField;
            }
            set {
                if ((this.PESOSACOField.Equals(value) != true)) {
                    this.PESOSACOField = value;
                    this.RaisePropertyChanged("PESOSACO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PORCRENDIMIENTO {
            get {
                return this.PORCRENDIMIENTOField;
            }
            set {
                if ((this.PORCRENDIMIENTOField.Equals(value) != true)) {
                    this.PORCRENDIMIENTOField = value;
                    this.RaisePropertyChanged("PORCRENDIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TARA {
            get {
                return this.TARAField;
            }
            set {
                if ((this.TARAField.Equals(value) != true)) {
                    this.TARAField = value;
                    this.RaisePropertyChanged("TARA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOCAFE {
            get {
                return this.TIPOCAFEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOCAFEField, value) != true)) {
                    this.TIPOCAFEField = value;
                    this.RaisePropertyChanged("TIPOCAFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIOMODIFICA {
            get {
                return this.USUARIOMODIFICAField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOMODIFICAField, value) != true)) {
                    this.USUARIOMODIFICAField = value;
                    this.RaisePropertyChanged("USUARIOMODIFICA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIOREGISTRO {
            get {
                return this.USUARIOREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOREGISTROField, value) != true)) {
                    this.USUARIOREGISTROField = value;
                    this.RaisePropertyChanged("USUARIOREGISTRO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_ReporteTicketPesada_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_ReporteTicketPesada_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCUSUARIOREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOCIDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DSCTOAGUAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHATICKETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HUMEDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDLABORATORIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPROCESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTICKETPESADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTICKETPESADAZONAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGBRUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGNETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal KGSECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCAL_LABORATORIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NROSACOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PESOSACOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RENDIMINETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TARAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALIDAD {
            get {
                return this.CALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.CALIDADField, value) != true)) {
                    this.CALIDADField = value;
                    this.RaisePropertyChanged("CALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCUSUARIOREGISTRO {
            get {
                return this.DESCUSUARIOREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCUSUARIOREGISTROField, value) != true)) {
                    this.DESCUSUARIOREGISTROField = value;
                    this.RaisePropertyChanged("DESCUSUARIOREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOCIDENTIDAD {
            get {
                return this.DOCIDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.DOCIDENTIDADField, value) != true)) {
                    this.DOCIDENTIDADField = value;
                    this.RaisePropertyChanged("DOCIDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DSCTOAGUA {
            get {
                return this.DSCTOAGUAField;
            }
            set {
                if ((this.DSCTOAGUAField.Equals(value) != true)) {
                    this.DSCTOAGUAField = value;
                    this.RaisePropertyChanged("DSCTOAGUA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHAREGISTRO {
            get {
                return this.FECHAREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAREGISTROField, value) != true)) {
                    this.FECHAREGISTROField = value;
                    this.RaisePropertyChanged("FECHAREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHATICKET {
            get {
                return this.FECHATICKETField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHATICKETField, value) != true)) {
                    this.FECHATICKETField = value;
                    this.RaisePropertyChanged("FECHATICKET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HUMEDAD {
            get {
                return this.HUMEDADField;
            }
            set {
                if ((object.ReferenceEquals(this.HUMEDADField, value) != true)) {
                    this.HUMEDADField = value;
                    this.RaisePropertyChanged("HUMEDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDESTADOField, value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDLABORATORIO {
            get {
                return this.IDLABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDLABORATORIOField, value) != true)) {
                    this.IDLABORATORIOField = value;
                    this.RaisePropertyChanged("IDLABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPROCESO {
            get {
                return this.IDPROCESOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPROCESOField, value) != true)) {
                    this.IDPROCESOField = value;
                    this.RaisePropertyChanged("IDPROCESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTICKETPESADA {
            get {
                return this.IDTICKETPESADAField;
            }
            set {
                if ((this.IDTICKETPESADAField.Equals(value) != true)) {
                    this.IDTICKETPESADAField = value;
                    this.RaisePropertyChanged("IDTICKETPESADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDTICKETPESADAZONA {
            get {
                return this.IDTICKETPESADAZONAField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTICKETPESADAZONAField, value) != true)) {
                    this.IDTICKETPESADAZONAField = value;
                    this.RaisePropertyChanged("IDTICKETPESADAZONA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGBRUTO {
            get {
                return this.KGBRUTOField;
            }
            set {
                if ((this.KGBRUTOField.Equals(value) != true)) {
                    this.KGBRUTOField = value;
                    this.RaisePropertyChanged("KGBRUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGNETO {
            get {
                return this.KGNETOField;
            }
            set {
                if ((this.KGNETOField.Equals(value) != true)) {
                    this.KGNETOField = value;
                    this.RaisePropertyChanged("KGNETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal KGSECO {
            get {
                return this.KGSECOField;
            }
            set {
                if ((this.KGSECOField.Equals(value) != true)) {
                    this.KGSECOField = value;
                    this.RaisePropertyChanged("KGSECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCAL {
            get {
                return this.LOCALField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCALField, value) != true)) {
                    this.LOCALField = value;
                    this.RaisePropertyChanged("LOCAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCAL_LABORATORIO {
            get {
                return this.LOCAL_LABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCAL_LABORATORIOField, value) != true)) {
                    this.LOCAL_LABORATORIOField = value;
                    this.RaisePropertyChanged("LOCAL_LABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NROSACO {
            get {
                return this.NROSACOField;
            }
            set {
                if ((this.NROSACOField.Equals(value) != true)) {
                    this.NROSACOField = value;
                    this.RaisePropertyChanged("NROSACO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PESOSACO {
            get {
                return this.PESOSACOField;
            }
            set {
                if ((this.PESOSACOField.Equals(value) != true)) {
                    this.PESOSACOField = value;
                    this.RaisePropertyChanged("PESOSACO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RENDIMINETO {
            get {
                return this.RENDIMINETOField;
            }
            set {
                if ((object.ReferenceEquals(this.RENDIMINETOField, value) != true)) {
                    this.RENDIMINETOField = value;
                    this.RaisePropertyChanged("RENDIMINETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TARA {
            get {
                return this.TARAField;
            }
            set {
                if ((this.TARAField.Equals(value) != true)) {
                    this.TARAField = value;
                    this.RaisePropertyChanged("TARA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTicketPesada.ITicketPesada")]
    public interface ITicketPesada {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/GetComp", ReplyAction="http://tempuri.org/ITicketPesada/GetCompResponse")]
        SGOTouch.ServiceTicketPesada.ComprobanteCliente[] GetComp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/GetComp", ReplyAction="http://tempuri.org/ITicketPesada/GetCompResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.ComprobanteCliente[]> GetCompAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_InsTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_InsTicketPesadaResponse")]
        int usp_InsTicketPesada(int TipoOperacion, SGOTouch.ServiceTicketPesada.TICKET_PESADA oBe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_InsTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_InsTicketPesadaResponse")]
        System.Threading.Tasks.Task<int> usp_InsTicketPesadaAsync(int TipoOperacion, SGOTouch.ServiceTicketPesada.TICKET_PESADA oBe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_LisTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_LisTicketPesadaResponse")]
        SGOTouch.ServiceTicketPesada.usp_LisTicketPesada_Result[] usp_LisTicketPesada(string strEstado, string strFiltro, string strIdlocal, string strFechaIncio, string strFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_LisTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_LisTicketPesadaResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.usp_LisTicketPesada_Result[]> usp_LisTicketPesadaAsync(string strEstado, string strFiltro, string strIdlocal, string strFechaIncio, string strFechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_ReporteTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_ReporteTicketPesadaResponse")]
        SGOTouch.ServiceTicketPesada.usp_ReporteTicketPesada_Result[] usp_ReporteTicketPesada(string strIdTicketPesada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketPesada/usp_ReporteTicketPesada", ReplyAction="http://tempuri.org/ITicketPesada/usp_ReporteTicketPesadaResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.usp_ReporteTicketPesada_Result[]> usp_ReporteTicketPesadaAsync(string strIdTicketPesada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicketPesadaChannel : SGOTouch.ServiceTicketPesada.ITicketPesada, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketPesadaClient : System.ServiceModel.ClientBase<SGOTouch.ServiceTicketPesada.ITicketPesada>, SGOTouch.ServiceTicketPesada.ITicketPesada {
        
        public TicketPesadaClient() {
        }
        
        public TicketPesadaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketPesadaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketPesadaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketPesadaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGOTouch.ServiceTicketPesada.ComprobanteCliente[] GetComp() {
            return base.Channel.GetComp();
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.ComprobanteCliente[]> GetCompAsync() {
            return base.Channel.GetCompAsync();
        }
        
        public int usp_InsTicketPesada(int TipoOperacion, SGOTouch.ServiceTicketPesada.TICKET_PESADA oBe) {
            return base.Channel.usp_InsTicketPesada(TipoOperacion, oBe);
        }
        
        public System.Threading.Tasks.Task<int> usp_InsTicketPesadaAsync(int TipoOperacion, SGOTouch.ServiceTicketPesada.TICKET_PESADA oBe) {
            return base.Channel.usp_InsTicketPesadaAsync(TipoOperacion, oBe);
        }
        
        public SGOTouch.ServiceTicketPesada.usp_LisTicketPesada_Result[] usp_LisTicketPesada(string strEstado, string strFiltro, string strIdlocal, string strFechaIncio, string strFechaFin) {
            return base.Channel.usp_LisTicketPesada(strEstado, strFiltro, strIdlocal, strFechaIncio, strFechaFin);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.usp_LisTicketPesada_Result[]> usp_LisTicketPesadaAsync(string strEstado, string strFiltro, string strIdlocal, string strFechaIncio, string strFechaFin) {
            return base.Channel.usp_LisTicketPesadaAsync(strEstado, strFiltro, strIdlocal, strFechaIncio, strFechaFin);
        }
        
        public SGOTouch.ServiceTicketPesada.usp_ReporteTicketPesada_Result[] usp_ReporteTicketPesada(string strIdTicketPesada) {
            return base.Channel.usp_ReporteTicketPesada(strIdTicketPesada);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTicketPesada.usp_ReporteTicketPesada_Result[]> usp_ReporteTicketPesadaAsync(string strIdTicketPesada) {
            return base.Channel.usp_ReporteTicketPesadaAsync(strIdTicketPesada);
        }
    }
}
