//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGOTouch.ServiceTablaGeneral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelLocalIdEmpresaUsuario", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class SelLocalIdEmpresaUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vDireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEmpresa {
            get {
                return this.IdEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEmpresaField, value) != true)) {
                    this.IdEmpresaField = value;
                    this.RaisePropertyChanged("IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idLocal {
            get {
                return this.idLocalField;
            }
            set {
                if ((object.ReferenceEquals(this.idLocalField, value) != true)) {
                    this.idLocalField = value;
                    this.RaisePropertyChanged("idLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nEstado {
            get {
                return this.nEstadoField;
            }
            set {
                if ((this.nEstadoField.Equals(value) != true)) {
                    this.nEstadoField = value;
                    this.RaisePropertyChanged("nEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDescripcion {
            get {
                return this.vDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.vDescripcionField, value) != true)) {
                    this.vDescripcionField = value;
                    this.RaisePropertyChanged("vDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vDireccion {
            get {
                return this.vDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.vDireccionField, value) != true)) {
                    this.vDireccionField = value;
                    this.RaisePropertyChanged("vDireccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPO_COSECHA", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class TIPO_COSECHA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsuarioModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vcComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vcCosechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModifica {
            get {
                return this.FechaModificaField;
            }
            set {
                if ((this.FechaModificaField.Equals(value) != true)) {
                    this.FechaModificaField = value;
                    this.RaisePropertyChanged("FechaModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCosecha {
            get {
                return this.IdCosechaField;
            }
            set {
                if ((this.IdCosechaField.Equals(value) != true)) {
                    this.IdCosechaField = value;
                    this.RaisePropertyChanged("IdCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsuarioModifica {
            get {
                return this.UsuarioModificaField;
            }
            set {
                if ((this.UsuarioModificaField.Equals(value) != true)) {
                    this.UsuarioModificaField = value;
                    this.RaisePropertyChanged("UsuarioModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((this.UsuarioRegistroField.Equals(value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vcComentario {
            get {
                return this.vcComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.vcComentarioField, value) != true)) {
                    this.vcComentarioField = value;
                    this.RaisePropertyChanged("vcComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vcCosecha {
            get {
                return this.vcCosechaField;
            }
            set {
                if ((object.ReferenceEquals(this.vcCosechaField, value) != true)) {
                    this.vcCosechaField = value;
                    this.RaisePropertyChanged("vcCosecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_Mant_TIPO_COSECHA_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_Mant_TIPO_COSECHA_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMENTARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VUSUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMENTARIO {
            get {
                return this.COMENTARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMENTARIOField, value) != true)) {
                    this.COMENTARIOField = value;
                    this.RaisePropertyChanged("COMENTARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCosecha {
            get {
                return this.IdCosechaField;
            }
            set {
                if ((this.IdCosechaField.Equals(value) != true)) {
                    this.IdCosechaField = value;
                    this.RaisePropertyChanged("IdCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado {
            get {
                return this.IdEstadoField;
            }
            set {
                if ((this.IdEstadoField.Equals(value) != true)) {
                    this.IdEstadoField = value;
                    this.RaisePropertyChanged("IdEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((this.UsuarioRegistroField.Equals(value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VUSUARIO {
            get {
                return this.VUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.VUSUARIOField, value) != true)) {
                    this.VUSUARIOField = value;
                    this.RaisePropertyChanged("VUSUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLIENTE_COSECHA", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class CLIENTE_COSECHA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InVigenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsuarioModificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModifica {
            get {
                return this.FechaModificaField;
            }
            set {
                if ((this.FechaModificaField.Equals(value) != true)) {
                    this.FechaModificaField = value;
                    this.RaisePropertyChanged("FechaModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClienteCosecha {
            get {
                return this.IdClienteCosechaField;
            }
            set {
                if ((this.IdClienteCosechaField.Equals(value) != true)) {
                    this.IdClienteCosechaField = value;
                    this.RaisePropertyChanged("IdClienteCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCosecha {
            get {
                return this.IdCosechaField;
            }
            set {
                if ((this.IdCosechaField.Equals(value) != true)) {
                    this.IdCosechaField = value;
                    this.RaisePropertyChanged("IdCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InEstado {
            get {
                return this.InEstadoField;
            }
            set {
                if ((this.InEstadoField.Equals(value) != true)) {
                    this.InEstadoField = value;
                    this.RaisePropertyChanged("InEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InVigente {
            get {
                return this.InVigenteField;
            }
            set {
                if ((this.InVigenteField.Equals(value) != true)) {
                    this.InVigenteField = value;
                    this.RaisePropertyChanged("InVigente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsuarioModifica {
            get {
                return this.UsuarioModificaField;
            }
            set {
                if ((this.UsuarioModificaField.Equals(value) != true)) {
                    this.UsuarioModificaField = value;
                    this.RaisePropertyChanged("UsuarioModifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((this.UsuarioRegistroField.Equals(value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_Mant_CLIENTE_COSECHA_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_Mant_CLIENTE_COSECHA_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCosechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTipoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InVigenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VUSUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocIdentidad {
            get {
                return this.DocIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIdentidadField, value) != true)) {
                    this.DocIdentidadField = value;
                    this.RaisePropertyChanged("DocIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClienteCosecha {
            get {
                return this.IdClienteCosechaField;
            }
            set {
                if ((this.IdClienteCosechaField.Equals(value) != true)) {
                    this.IdClienteCosechaField = value;
                    this.RaisePropertyChanged("IdClienteCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCosecha {
            get {
                return this.IdCosechaField;
            }
            set {
                if ((this.IdCosechaField.Equals(value) != true)) {
                    this.IdCosechaField = value;
                    this.RaisePropertyChanged("IdCosecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTipoCliente {
            get {
                return this.IdTipoClienteField;
            }
            set {
                if ((this.IdTipoClienteField.Equals(value) != true)) {
                    this.IdTipoClienteField = value;
                    this.RaisePropertyChanged("IdTipoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InEstado {
            get {
                return this.InEstadoField;
            }
            set {
                if ((this.InEstadoField.Equals(value) != true)) {
                    this.InEstadoField = value;
                    this.RaisePropertyChanged("InEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InVigente {
            get {
                return this.InVigenteField;
            }
            set {
                if ((this.InVigenteField.Equals(value) != true)) {
                    this.InVigenteField = value;
                    this.RaisePropertyChanged("InVigente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_CLIENTE {
            get {
                return this.TIPO_CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_CLIENTEField, value) != true)) {
                    this.TIPO_CLIENTEField = value;
                    this.RaisePropertyChanged("TIPO_CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((this.UsuarioRegistroField.Equals(value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VUSUARIO {
            get {
                return this.VUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.VUSUARIOField, value) != true)) {
                    this.VUSUARIOField = value;
                    this.RaisePropertyChanged("VUSUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisTipoCafe_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisTipoCafe_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTIPOCAFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VUSUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAREGISTRO {
            get {
                return this.FECHAREGISTROField;
            }
            set {
                if ((this.FECHAREGISTROField.Equals(value) != true)) {
                    this.FECHAREGISTROField = value;
                    this.RaisePropertyChanged("FECHAREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((this.IDESTADOField.Equals(value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTIPOCAFE {
            get {
                return this.IDTIPOCAFEField;
            }
            set {
                if ((this.IDTIPOCAFEField.Equals(value) != true)) {
                    this.IDTIPOCAFEField = value;
                    this.RaisePropertyChanged("IDTIPOCAFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VUSUARIO {
            get {
                return this.VUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.VUSUARIOField, value) != true)) {
                    this.VUSUARIOField = value;
                    this.RaisePropertyChanged("VUSUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisComboSacoCafe_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisComboSacoCafe_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisLaboratorioDisponibleXCliente_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisLaboratorioDisponibleXCliente_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoLaboratorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLaboratorioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoLaboratorio {
            get {
                return this.CodigoLaboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoLaboratorioField, value) != true)) {
                    this.CodigoLaboratorioField = value;
                    this.RaisePropertyChanged("CodigoLaboratorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLaboratorio {
            get {
                return this.IdLaboratorioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLaboratorioField, value) != true)) {
                    this.IdLaboratorioField = value;
                    this.RaisePropertyChanged("IdLaboratorio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisTipoRuma_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisTipoRuma_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTIPORUMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VUSUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAREGISTRO {
            get {
                return this.FECHAREGISTROField;
            }
            set {
                if ((this.FECHAREGISTROField.Equals(value) != true)) {
                    this.FECHAREGISTROField = value;
                    this.RaisePropertyChanged("FECHAREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((this.IDESTADOField.Equals(value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTIPORUMA {
            get {
                return this.IDTIPORUMAField;
            }
            set {
                if ((this.IDTIPORUMAField.Equals(value) != true)) {
                    this.IDTIPORUMAField = value;
                    this.RaisePropertyChanged("IDTIPORUMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VUSUARIO {
            get {
                return this.VUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.VUSUARIOField, value) != true)) {
                    this.VUSUARIOField = value;
                    this.RaisePropertyChanged("VUSUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisBusquedaClienteFiltro_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisBusquedaClienteFiltro_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPARTAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOCIDENTIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCLIENTESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDEXCELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_DOCUMENTOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLIENTE {
            get {
                return this.CLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTEField, value) != true)) {
                    this.CLIENTEField = value;
                    this.RaisePropertyChanged("CLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPARTAMENTO {
            get {
                return this.DEPARTAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPARTAMENTOField, value) != true)) {
                    this.DEPARTAMENTOField = value;
                    this.RaisePropertyChanged("DEPARTAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOCIDENTIDAD {
            get {
                return this.DOCIDENTIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.DOCIDENTIDADField, value) != true)) {
                    this.DOCIDENTIDADField = value;
                    this.RaisePropertyChanged("DOCIDENTIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCLIENTE {
            get {
                return this.IDCLIENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCLIENTEField, value) != true)) {
                    this.IDCLIENTEField = value;
                    this.RaisePropertyChanged("IDCLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLIENTESGO {
            get {
                return this.IDCLIENTESGOField;
            }
            set {
                if ((this.IDCLIENTESGOField.Equals(value) != true)) {
                    this.IDCLIENTESGOField = value;
                    this.RaisePropertyChanged("IDCLIENTESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDEXCEL {
            get {
                return this.IDEXCELField;
            }
            set {
                if ((object.ReferenceEquals(this.IDEXCELField, value) != true)) {
                    this.IDEXCELField = value;
                    this.RaisePropertyChanged("IDEXCEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_DOCUMENTO {
            get {
                return this.TIPO_DOCUMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_DOCUMENTOField, value) != true)) {
                    this.TIPO_DOCUMENTOField = value;
                    this.RaisePropertyChanged("TIPO_DOCUMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisContratoConGI_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisContratoConGI_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMBOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCONTRATOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMBO {
            get {
                return this.COMBOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMBOField, value) != true)) {
                    this.COMBOField = value;
                    this.RaisePropertyChanged("COMBO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCONTRATO {
            get {
                return this.IDCONTRATOField;
            }
            set {
                if ((this.IDCONTRATOField.Equals(value) != true)) {
                    this.IDCONTRATOField = value;
                    this.RaisePropertyChanged("IDCONTRATO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTablaGeneral.ITablaGeneral")]
    public interface ITablaGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_SelLocalIdEmpresaUsuario", ReplyAction="http://tempuri.org/ITablaGeneral/usp_SelLocalIdEmpresaUsuarioResponse")]
        SGOTouch.ServiceTablaGeneral.SelLocalIdEmpresaUsuario[] usp_SelLocalIdEmpresaUsuario(string IdEmpresa, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_SelLocalIdEmpresaUsuario", ReplyAction="http://tempuri.org/ITablaGeneral/usp_SelLocalIdEmpresaUsuarioResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.SelLocalIdEmpresaUsuario[]> usp_SelLocalIdEmpresaUsuarioAsync(string IdEmpresa, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_Mant_TIPO_COSECHA", ReplyAction="http://tempuri.org/ITablaGeneral/usp_Mant_TIPO_COSECHAResponse")]
        SGOTouch.ServiceTablaGeneral.usp_Mant_TIPO_COSECHA_Result[] usp_Mant_TIPO_COSECHA(int bus, SGOTouch.ServiceTablaGeneral.TIPO_COSECHA oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_Mant_TIPO_COSECHA", ReplyAction="http://tempuri.org/ITablaGeneral/usp_Mant_TIPO_COSECHAResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_Mant_TIPO_COSECHA_Result[]> usp_Mant_TIPO_COSECHAAsync(int bus, SGOTouch.ServiceTablaGeneral.TIPO_COSECHA oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_Mant_CLIENTE_COSECHA", ReplyAction="http://tempuri.org/ITablaGeneral/usp_Mant_CLIENTE_COSECHAResponse")]
        SGOTouch.ServiceTablaGeneral.usp_Mant_CLIENTE_COSECHA_Result[] usp_Mant_CLIENTE_COSECHA(int bus, SGOTouch.ServiceTablaGeneral.CLIENTE_COSECHA oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_Mant_CLIENTE_COSECHA", ReplyAction="http://tempuri.org/ITablaGeneral/usp_Mant_CLIENTE_COSECHAResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_Mant_CLIENTE_COSECHA_Result[]> usp_Mant_CLIENTE_COSECHAAsync(int bus, SGOTouch.ServiceTablaGeneral.CLIENTE_COSECHA oP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisTipoCafe", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisTipoCafeResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisTipoCafe_Result[] usp_LisTipoCafe(string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisTipoCafe", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisTipoCafeResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisTipoCafe_Result[]> usp_LisTipoCafeAsync(string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisComboSacoCafe", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisComboSacoCafeResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisComboSacoCafe_Result[] usp_LisComboSacoCafe(string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisComboSacoCafe", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisComboSacoCafeResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisComboSacoCafe_Result[]> usp_LisComboSacoCafeAsync(string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisLaboratorioDisponibleXCliente", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisLaboratorioDisponibleXClienteResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisLaboratorioDisponibleXCliente_Result[] usp_LisLaboratorioDisponibleXCliente(int inIdCliente, string strIdLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisLaboratorioDisponibleXCliente", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisLaboratorioDisponibleXClienteResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisLaboratorioDisponibleXCliente_Result[]> usp_LisLaboratorioDisponibleXClienteAsync(int inIdCliente, string strIdLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisTipoRuma", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisTipoRumaResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisTipoRuma_Result[] usp_LisTipoRuma(string strIdLocal, string strIdEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisTipoRuma", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisTipoRumaResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisTipoRuma_Result[]> usp_LisTipoRumaAsync(string strIdLocal, string strIdEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisBusquedaClienteFiltro", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisBusquedaClienteFiltroResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisBusquedaClienteFiltro_Result[] usp_LisBusquedaClienteFiltro(string strFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisBusquedaClienteFiltro", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisBusquedaClienteFiltroResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisBusquedaClienteFiltro_Result[]> usp_LisBusquedaClienteFiltroAsync(string strFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisContratoConGI", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisContratoConGIResponse")]
        SGOTouch.ServiceTablaGeneral.usp_LisContratoConGI_Result[] usp_LisContratoConGI(int inIdCliente, int inCosecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITablaGeneral/usp_LisContratoConGI", ReplyAction="http://tempuri.org/ITablaGeneral/usp_LisContratoConGIResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisContratoConGI_Result[]> usp_LisContratoConGIAsync(int inIdCliente, int inCosecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITablaGeneralChannel : SGOTouch.ServiceTablaGeneral.ITablaGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TablaGeneralClient : System.ServiceModel.ClientBase<SGOTouch.ServiceTablaGeneral.ITablaGeneral>, SGOTouch.ServiceTablaGeneral.ITablaGeneral {
        
        public TablaGeneralClient() {
        }
        
        public TablaGeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TablaGeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TablaGeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TablaGeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGOTouch.ServiceTablaGeneral.SelLocalIdEmpresaUsuario[] usp_SelLocalIdEmpresaUsuario(string IdEmpresa, int IdUsuario) {
            return base.Channel.usp_SelLocalIdEmpresaUsuario(IdEmpresa, IdUsuario);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.SelLocalIdEmpresaUsuario[]> usp_SelLocalIdEmpresaUsuarioAsync(string IdEmpresa, int IdUsuario) {
            return base.Channel.usp_SelLocalIdEmpresaUsuarioAsync(IdEmpresa, IdUsuario);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_Mant_TIPO_COSECHA_Result[] usp_Mant_TIPO_COSECHA(int bus, SGOTouch.ServiceTablaGeneral.TIPO_COSECHA oP) {
            return base.Channel.usp_Mant_TIPO_COSECHA(bus, oP);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_Mant_TIPO_COSECHA_Result[]> usp_Mant_TIPO_COSECHAAsync(int bus, SGOTouch.ServiceTablaGeneral.TIPO_COSECHA oP) {
            return base.Channel.usp_Mant_TIPO_COSECHAAsync(bus, oP);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_Mant_CLIENTE_COSECHA_Result[] usp_Mant_CLIENTE_COSECHA(int bus, SGOTouch.ServiceTablaGeneral.CLIENTE_COSECHA oP) {
            return base.Channel.usp_Mant_CLIENTE_COSECHA(bus, oP);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_Mant_CLIENTE_COSECHA_Result[]> usp_Mant_CLIENTE_COSECHAAsync(int bus, SGOTouch.ServiceTablaGeneral.CLIENTE_COSECHA oP) {
            return base.Channel.usp_Mant_CLIENTE_COSECHAAsync(bus, oP);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisTipoCafe_Result[] usp_LisTipoCafe(string strEstado) {
            return base.Channel.usp_LisTipoCafe(strEstado);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisTipoCafe_Result[]> usp_LisTipoCafeAsync(string strEstado) {
            return base.Channel.usp_LisTipoCafeAsync(strEstado);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisComboSacoCafe_Result[] usp_LisComboSacoCafe(string strEstado) {
            return base.Channel.usp_LisComboSacoCafe(strEstado);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisComboSacoCafe_Result[]> usp_LisComboSacoCafeAsync(string strEstado) {
            return base.Channel.usp_LisComboSacoCafeAsync(strEstado);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisLaboratorioDisponibleXCliente_Result[] usp_LisLaboratorioDisponibleXCliente(int inIdCliente, string strIdLocal) {
            return base.Channel.usp_LisLaboratorioDisponibleXCliente(inIdCliente, strIdLocal);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisLaboratorioDisponibleXCliente_Result[]> usp_LisLaboratorioDisponibleXClienteAsync(int inIdCliente, string strIdLocal) {
            return base.Channel.usp_LisLaboratorioDisponibleXClienteAsync(inIdCliente, strIdLocal);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisTipoRuma_Result[] usp_LisTipoRuma(string strIdLocal, string strIdEstado) {
            return base.Channel.usp_LisTipoRuma(strIdLocal, strIdEstado);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisTipoRuma_Result[]> usp_LisTipoRumaAsync(string strIdLocal, string strIdEstado) {
            return base.Channel.usp_LisTipoRumaAsync(strIdLocal, strIdEstado);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisBusquedaClienteFiltro_Result[] usp_LisBusquedaClienteFiltro(string strFiltro) {
            return base.Channel.usp_LisBusquedaClienteFiltro(strFiltro);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisBusquedaClienteFiltro_Result[]> usp_LisBusquedaClienteFiltroAsync(string strFiltro) {
            return base.Channel.usp_LisBusquedaClienteFiltroAsync(strFiltro);
        }
        
        public SGOTouch.ServiceTablaGeneral.usp_LisContratoConGI_Result[] usp_LisContratoConGI(int inIdCliente, int inCosecha) {
            return base.Channel.usp_LisContratoConGI(inIdCliente, inCosecha);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceTablaGeneral.usp_LisContratoConGI_Result[]> usp_LisContratoConGIAsync(int inIdCliente, int inCosecha) {
            return base.Channel.usp_LisContratoConGIAsync(inIdCliente, inCosecha);
        }
    }
}
