//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGOTouch.ServiceCertificadoVSP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usp_LisSaldoCertificado_Result", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class usp_LisSaldoCertificado_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> COSECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCERTIFICADOVSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LIMITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OPERACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SALDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SALDO_CALCULADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SOBREGIROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TOPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> COSECHA {
            get {
                return this.COSECHAField;
            }
            set {
                if ((this.COSECHAField.Equals(value) != true)) {
                    this.COSECHAField = value;
                    this.RaisePropertyChanged("COSECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCERTIFICADOVSP {
            get {
                return this.IDCERTIFICADOVSPField;
            }
            set {
                if ((this.IDCERTIFICADOVSPField.Equals(value) != true)) {
                    this.IDCERTIFICADOVSPField = value;
                    this.RaisePropertyChanged("IDCERTIFICADOVSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LIMITE {
            get {
                return this.LIMITEField;
            }
            set {
                if ((this.LIMITEField.Equals(value) != true)) {
                    this.LIMITEField = value;
                    this.RaisePropertyChanged("LIMITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OPERACION {
            get {
                return this.OPERACIONField;
            }
            set {
                if ((this.OPERACIONField.Equals(value) != true)) {
                    this.OPERACIONField = value;
                    this.RaisePropertyChanged("OPERACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SALDO {
            get {
                return this.SALDOField;
            }
            set {
                if ((this.SALDOField.Equals(value) != true)) {
                    this.SALDOField = value;
                    this.RaisePropertyChanged("SALDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SALDO_CALCULADO {
            get {
                return this.SALDO_CALCULADOField;
            }
            set {
                if ((this.SALDO_CALCULADOField.Equals(value) != true)) {
                    this.SALDO_CALCULADOField = value;
                    this.RaisePropertyChanged("SALDO_CALCULADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOBREGIRO {
            get {
                return this.SOBREGIROField;
            }
            set {
                if ((this.SOBREGIROField.Equals(value) != true)) {
                    this.SOBREGIROField = value;
                    this.RaisePropertyChanged("SOBREGIRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TOPE {
            get {
                return this.TOPEField;
            }
            set {
                if ((this.TOPEField.Equals(value) != true)) {
                    this.TOPEField = value;
                    this.RaisePropertyChanged("TOPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCertificadoVSP.ICertificadoVSP")]
    public interface ICertificadoVSP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificadoVSP/usp_LisSaldoCertificado", ReplyAction="http://tempuri.org/ICertificadoVSP/usp_LisSaldoCertificadoResponse")]
        SGOTouch.ServiceCertificadoVSP.usp_LisSaldoCertificado_Result[] usp_LisSaldoCertificado(int IdCliente, string strCosecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICertificadoVSP/usp_LisSaldoCertificado", ReplyAction="http://tempuri.org/ICertificadoVSP/usp_LisSaldoCertificadoResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceCertificadoVSP.usp_LisSaldoCertificado_Result[]> usp_LisSaldoCertificadoAsync(int IdCliente, string strCosecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICertificadoVSPChannel : SGOTouch.ServiceCertificadoVSP.ICertificadoVSP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificadoVSPClient : System.ServiceModel.ClientBase<SGOTouch.ServiceCertificadoVSP.ICertificadoVSP>, SGOTouch.ServiceCertificadoVSP.ICertificadoVSP {
        
        public CertificadoVSPClient() {
        }
        
        public CertificadoVSPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificadoVSPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadoVSPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadoVSPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGOTouch.ServiceCertificadoVSP.usp_LisSaldoCertificado_Result[] usp_LisSaldoCertificado(int IdCliente, string strCosecha) {
            return base.Channel.usp_LisSaldoCertificado(IdCliente, strCosecha);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceCertificadoVSP.usp_LisSaldoCertificado_Result[]> usp_LisSaldoCertificadoAsync(int IdCliente, string strCosecha) {
            return base.Channel.usp_LisSaldoCertificadoAsync(IdCliente, strCosecha);
        }
    }
}
