//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGOTouch.ServiceCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LisClienteContacto", Namespace="http://schemas.datacontract.org/2004/07/Persistence.domain")]
    [System.SerializableAttribute()]
    public partial class LisClienteContacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCAREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCCARGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONFACTURAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECCIONREFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDAREAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCARGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCONTACTOCLIENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOREGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VUSUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO {
            get {
                return this.APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOField, value) != true)) {
                    this.APELLIDOField = value;
                    this.RaisePropertyChanged("APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO {
            get {
                return this.CORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREOField, value) != true)) {
                    this.CORREOField = value;
                    this.RaisePropertyChanged("CORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCAREA {
            get {
                return this.DESCAREAField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCAREAField, value) != true)) {
                    this.DESCAREAField = value;
                    this.RaisePropertyChanged("DESCAREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCCARGO {
            get {
                return this.DESCCARGOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCCARGOField, value) != true)) {
                    this.DESCCARGOField = value;
                    this.RaisePropertyChanged("DESCCARGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCIONFACTURA {
            get {
                return this.DIRECCIONFACTURAField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONFACTURAField, value) != true)) {
                    this.DIRECCIONFACTURAField = value;
                    this.RaisePropertyChanged("DIRECCIONFACTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCIONREFERENCIA {
            get {
                return this.DIRECCIONREFERENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECCIONREFERENCIAField, value) != true)) {
                    this.DIRECCIONREFERENCIAField = value;
                    this.RaisePropertyChanged("DIRECCIONREFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAREGISTRO {
            get {
                return this.FECHAREGISTROField;
            }
            set {
                if ((this.FECHAREGISTROField.Equals(value) != true)) {
                    this.FECHAREGISTROField = value;
                    this.RaisePropertyChanged("FECHAREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDAREA {
            get {
                return this.IDAREAField;
            }
            set {
                if ((this.IDAREAField.Equals(value) != true)) {
                    this.IDAREAField = value;
                    this.RaisePropertyChanged("IDAREA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCARGO {
            get {
                return this.IDCARGOField;
            }
            set {
                if ((this.IDCARGOField.Equals(value) != true)) {
                    this.IDCARGOField = value;
                    this.RaisePropertyChanged("IDCARGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLIENTE {
            get {
                return this.IDCLIENTEField;
            }
            set {
                if ((this.IDCLIENTEField.Equals(value) != true)) {
                    this.IDCLIENTEField = value;
                    this.RaisePropertyChanged("IDCLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCONTACTOCLIENTE {
            get {
                return this.IDCONTACTOCLIENTEField;
            }
            set {
                if ((this.IDCONTACTOCLIENTEField.Equals(value) != true)) {
                    this.IDCONTACTOCLIENTEField = value;
                    this.RaisePropertyChanged("IDCONTACTOCLIENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESTADO {
            get {
                return this.IDESTADOField;
            }
            set {
                if ((this.IDESTADOField.Equals(value) != true)) {
                    this.IDESTADOField = value;
                    this.RaisePropertyChanged("IDESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO {
            get {
                return this.TELEFONOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONOField, value) != true)) {
                    this.TELEFONOField = value;
                    this.RaisePropertyChanged("TELEFONO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIOREGISTRO {
            get {
                return this.USUARIOREGISTROField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOREGISTROField, value) != true)) {
                    this.USUARIOREGISTROField = value;
                    this.RaisePropertyChanged("USUARIOREGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VUSUARIO {
            get {
                return this.VUSUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.VUSUARIOField, value) != true)) {
                    this.VUSUARIOField = value;
                    this.RaisePropertyChanged("VUSUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.ICliente")]
    public interface ICliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/usp_LisClienteContacto", ReplyAction="http://tempuri.org/ICliente/usp_LisClienteContactoResponse")]
        SGOTouch.ServiceCliente.LisClienteContacto[] usp_LisClienteContacto(System.Nullable<int> inIdCliente, string strEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICliente/usp_LisClienteContacto", ReplyAction="http://tempuri.org/ICliente/usp_LisClienteContactoResponse")]
        System.Threading.Tasks.Task<SGOTouch.ServiceCliente.LisClienteContacto[]> usp_LisClienteContactoAsync(System.Nullable<int> inIdCliente, string strEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteChannel : SGOTouch.ServiceCliente.ICliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteClient : System.ServiceModel.ClientBase<SGOTouch.ServiceCliente.ICliente>, SGOTouch.ServiceCliente.ICliente {
        
        public ClienteClient() {
        }
        
        public ClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGOTouch.ServiceCliente.LisClienteContacto[] usp_LisClienteContacto(System.Nullable<int> inIdCliente, string strEstado) {
            return base.Channel.usp_LisClienteContacto(inIdCliente, strEstado);
        }
        
        public System.Threading.Tasks.Task<SGOTouch.ServiceCliente.LisClienteContacto[]> usp_LisClienteContactoAsync(System.Nullable<int> inIdCliente, string strEstado) {
            return base.Channel.usp_LisClienteContactoAsync(inIdCliente, strEstado);
        }
    }
}
